### ISSUE TITLE
OSError: It looks like the config file at 'checkpoints/stable-diffusion-v1-5' is not a valid JSON file

### ISSUE THREAD

**Issue by nbansal90** [dreamoving/Phantom#2]
Hello, 

I am getting this error:
`OSError: It looks like the config file at 'checkpoints/stable-diffusion-v1-5' is not a valid JSON file` 
on running the command `python gradio2.py`.

I have followed all the steps mentioned in the `Installation` for manual installation. But still, I am getting this error. Plz help.

Apart from this, I am mostly looking to run inference on example text-heavy images. Is there any step-to-step guide to run inference on my custom data and store the results?

Regards,
Nitin Bansal

**Comment by fangxia1997** [comment]
I did not encounter this error during testing. There should be a file named model_index.json in the directory stable-diffusion-v1-5. Make sure the file is the same as the one on huggingface. And also you may check the diffusers version (required 0.21.4) and whether the checkpoint path is correct.

For step-to-step guide to run inference on my custom data and store the results, simply you can change the code on your own. The demo code provided is based on gradio, you can remove this part and save the output image just using openCV or Pillow.

**Comment by nbansal90** [comment]
Thanks @fangxia1997 for your prompt reply! Looks like I might be doing something wrong here. I will just state steps followed by me (as understood by me).

1. Go to the Huggingface([huggingface](https://huggingface.co/runwayml/stable-diffusion-v1-5)) website to download the stable diffusion model.
2. I scroll down till i See the following:
<img width="731" alt="image" src="https://github.com/dreamoving/Phantom/assets/12581965/b85bd2ad-3328-4fac-8c57-80203ae398de">

3. I then download the model `[v1-5-pruned-emaonly.ckpt](https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.ckpt)` and renamed it as `stable-diffusion-v1-5` and put it under `checkpoints ` folder.
4. Run the `gradio2.py` file and then I receive the error.


Am I missing something here or doing something wrong ? Because I do not find the file:

- `model_index.json`

- and not sure how do i download the specific model as mentioned by you `0.21.4`

Please advise!
Thank you.

**Comment by fangxia1997** [comment]
I think you should go to this website https://huggingface.co/runwayml/stable-diffusion-v1-5 , and clone the whole files and checkpoints using git (lfs) clone https://huggingface.co/runwayml/stable-diffusion-v1-5. Then you will get a folder named stable-diffusion-v1.5, which includes files like shown in https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main. Then you will find the file model_index.json

**Comment by nbansal90** [comment]
Thank you @fangxia1997! I got it right now.
